### ISSUE TITLE
贡献统计不准确

### ISSUE THREAD

**Issue by ivchen116** [ivchen116/knowledge-center#4]
问题场景：onenote 一篇文章，同一个人写两段文字时，贡献值会重复统计，导致统计不准确。

**Comment by ivchen116** [comment]
有文章作者统计不准确，参见《TAU 适配层手动修改》

**Comment by ghost** [comment]
- 在我的环境上，没有出现统计不正确的现象。针对《TAU适配层手动修改》在gen latest xlsx文章统计阶段该文在统计excel中只出现一个条目，在gen latest ppt也没有出现统计成多个条目的情况。

- 再次确认后跟踪。

**Comment by ivchen116** [comment]
1、手动构造场景测试下
2、作者统计好像有遗漏

**Comment by ivchen116** [comment]
需要循环统计所有Outline/OE下的 author，由于涉及场景较多，且目前基本够用，暂时不考虑优化。
